### ISSUE TITLE
Item description attribute doesn't update

### ISSUE THREAD

**Issue by VietnamNeko** [moddio/moddio2#482]
The item's description doesn't update the attributes it displays unless something else calls an update

**Comment by 420kyle69** [comment]
It seems like uncommenting lines 289-294 of AttributeComponent.js will fix this, but with line 290 removed because items don't have an updateAttributeBar method.
https://github.com/moddio/taro2/blob/7dfb0b98bdf44194421a446ef8e26ea6d0e1ff57/src/gameClasses/components/unit/AttributeComponent.js#L289-L294

**Comment by 420kyle69** [comment]
That change seems to solve it. I can't test it locally because descriptions don't show in localhost for some reason, but I went on a modd.io game, tested changing AttributeComponent.prototype.update to a function definition with this change made and it works.
